alias c clear
alias d 'docker'
alias dcup 'docker-compose up'
alias ddisable 'systemctl disable docker'
alias ddown 'docker-compose down'
alias denable 'systemctl enable docker'
alias drmi-dang 'docker rmi (docker images -q -f dangling=true)'
alias drmi-un 'docker rmi (docker images | grep \'^<none>\' | awk \'{print $3}\')'
alias dstart 'systemctl start docker'
alias dstop 'systemctl stop docker'
alias e 'emacsclient -c -t'
alias exifsort 'exiftool -r \'-Directory<DateTimeOriginal\' -d \'%Y/%Y-%m/%Y-%m-%d\''
alias g 'git'
alias ga 'git add'
alias gc 'git commit -m'
alias gd 'git diff'
alias gs 'git status'
alias j 'sudo journalctl'
alias jboot 'sudo journalctl -b'
alias jexec 'sudo journalctl'
alias jfollow 'sudo journalctl -f'
alias junit 'sudo journalctl -u'
alias k 'kubectl'
alias ntree 'nix-store -q --tree'
alias r 'sudo (command -s fish)'
alias s 'sudo'
alias srestart 'sudo systemctl restart'
alias sstart 'sudo systemctl start'
alias sstatus 'sudo systemctl status'
alias sstop 'sudo systemctl stop'
alias y 'yaourt'
